// item/src/components/Footer/index.vue
<template>
    <footer id="footer">
        <a class="footer-item" :class="{on:$route.path==='/index'}" @click="goto('/index')">
            <span class="item_icon">
                <i class="iconfont icon-shouye"></i>
            </span>
            <span>首页</span>
        </a>
        <a class="footer-item" :class="{on:$route.path==='/category'}" @click="goto('/category')">
            <span class="item_icon">
                <i class="iconfont icon-choutigui"></i>
            </span>
            <span>分类</span>
        </a>
        <a class="footer-item" :class="{on:$route.path==='/goods'}" @click="goto('/goods')">
            <span class="item_icon">
                <i class="iconfont icon-tupian"></i>
            </span>
            <span>值得买</span>
        </a>
        <a class="footer-item" :class="{on:$route.path==='/cart'}" @click="goto('/cart')">
            <span class="item_icon">
                <i class="iconfont icon-gouwuche"></i>
            </span>
            <span>购物车</span>
        </a>
        <a class="footer-item" :class="{on:$route.path==='/personal'}" @click="goto('/personal')">
            <span class="item_icon">
                <i class="iconfont icon-geren"></i>
            </span>
            <span>个人</span>
        </a>
    </footer>
</template>

<script>
export default {
    name: 'Footer',
    data() {
        return {}
    },
    methods: {
        goto(path) {
            // 为了防止用户多点，做限制
            if (this.$route.path !== path) {
                this.$router.replace(path)
            }
        }
    }
}
</script>
<style lang="stylus" rel="stylesheet/stylus">
#footer
    width 100%
    height 50px
    position fixed
    bottom 0
    display flex
    background-color #fff
    z-index 999
    .footer-item
        display flex
        flex 1
        text-align center
        flex-direction column
        align-items center
        margin 5px
        color #999999
        &.on
            color red
        span
            font-size 12px
            margin-top 2px
            margin-bottom 2px
            .iconfont
                font-size 22px
</style>

// item2/src/components/Footer/index.jsx
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'

import './css/index.css'

export default class Footer extends Component {
    render() {
        return (
            <footer id="footer">
                <NavLink to="/index" className="footer-item" activeClassName="on" >
                    <span className="item_icon">
                        <i className="iconfont icon-shouye"></i>
                    </span>
                    <span>首页</span>
                </NavLink>
                <NavLink to="/item" className="footer-item" activeClassName="on" >
                    <span className="item_icon">
                        <i className="iconfont icon-choutigui"></i>
                    </span>
                    <span>分类</span>
                </NavLink >
                <NavLink to="/topic" className="footer-item" activeClassName="on" >
                    <span className="item_icon">
                        <i className="iconfont icon-tupian"></i>
                    </span>
                    <span>值得买</span>
                </NavLink >
                <NavLink to="cart" className="footer-item" activeClassName="on" >
                    <span className="item_icon">
                        <i className="iconfont icon-gouwuche"></i>
                    </span>
                    <span>购物车</span>
                </NavLink >
                <NavLink to="personal" className="footer-item" activeClassName="on" >
                    <span className="item_icon">
                        <i className="iconfont icon-geren"></i>
                    </span>
                    <span>个人</span>
                </NavLink >
            </footer >
        )
    }
}
